# General app metadata
name: app-name              # Application name (used for naming resources)
namespace: media            # Namespace for the application, PVCs, and services

# Domain configuration
domain: sulibot.com         # Default domain for the application (override if needed)

# Docker container settings
image:
  repository: my-container-repo
  tag: latest

# Timezone
timezone: "America/Los_Angeles"  # Default timezone for the application

# Replicas
replicaCount: 1

# Ports
ports:
  servicePort: 80           # Port exposed by the service
  targetPort: 8080

# Gateway configuration
gateway:
  name: gateway-internal    # Optional: Defaults to "gateway-internal"
  namespace: network        # Namespace where the Gateway and HTTPRoute reside

# Deployment resources
resources:
  enabled: false            # Resource limits and requests are disabled by default
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Config PVC configuration
config:
  enabled: true              # PVC is enabled by default
  resources:
    requests:
      # storage: 5Gi         # Optional: Defaults to 1Gi if not set
  mountPath: /config         # Default mount path for config PVC

# Shared PVC configuration
sharedMedia:
  enabled: true              # Shared PVC is enabled by default
  mountPath: /media          # The path where the shared PVC will be mounted

# Probes for container health checks
probes:
  liveness:
    enabled: true
    path: /healthz
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readiness:
    enabled: true
    path: /ready
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startup:
    enabled: false
    path: /startup
    port: 8080
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
