###############################################################################
# General Application Settings
###############################################################################
name: app-name                  # Default application name
namespace: media                # Namespace for the application

###############################################################################
# Container/Image Settings
###############################################################################
image:
  repository: my-container-repo
  tag: latest                   # Image tag for the container
  pullPolicy: IfNotPresent      # Image pull policy

###############################################################################
# Replica and Port Configuration
###############################################################################
replicaCount: 1

ports:
  servicePort: 80               # Port exposed by the service
  targetPort: 8080              # Target port in the container

###############################################################################
# Timezone
###############################################################################
timezone: "America/Los_Angeles"   # Default timezone for the application

###############################################################################
# DNS Settings
###############################################################################
dnsPolicy: ClusterFirst       # Default DNS policy
dnsConfig:
  enabled: false                # Enable/disable custom DNS settings
  options:
    - name: ndots
      value: "1"

###############################################################################
# Persistent Volume Claims (PVCs)
###############################################################################
config:
  enabled: false                # Enable/disable Config PVC
  mountPath: /config            # Mount path for the Config PVC
  storageSize: 100Mi            # Default size for the Config PVC

data:
  enabled: true                 # Enable/disable Data PVC
  mountPath: /data              # Mount path for the Data PVC
  storageSize: 10Gi             # Size of the Data PVC

###############################################################################
# Security Contexts
###############################################################################
podSecurityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
# Uncomment and adjust below if you need additional container capabilities
#  config:
#    capabilities:
#      add:
#        - SETGID

###############################################################################
# Resource Limits and Requests
###############################################################################
resources:
  enabled: false                # Enable/disable resource settings
  requests:
    memory: "256Mi"             # Memory request for the container
    cpu: "250m"                 # CPU request for the container
  limits:
    memory: "512Mi"             # Memory limit for the container
    cpu: "500m"                 # CPU limit for the container

###############################################################################
# Global Networking Options
###############################################################################
networking:
  ipFamilyPolicy: PreferDualStack  # Options: PreferDualStack, RequireDualStack, or SingleStack
  singleStackIPFamily: IPv4        # Used only if ipFamilyPolicy is set to SingleStack

###############################################################################
# Tolerations and Affinity Rules
###############################################################################
tolerations: []                 # Define tolerations for node taints

affinity:
  enabled: true                 # Set to true to enable affinity rules; false to disable them entirely.
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: {}  # Provide an empty object by default
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: topology.kubernetes.io/host
              operator: In
              values:
                - pve01
                - pve02
                - pve03
      - weight: 1
        preference:
          matchExpressions:
            - key: intel.feature.node.kubernetes.io/gpu
              operator: In
              values:
                - "true"
#  podAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      labelSelector:
#        matchLabels:
#          app: "my-app"
#  # Optional: define pod anti-affinity rules if needed
#  podAntiAffinity: {}           

###############################################################################
# Service, Ingress, and Gateway Configuration
###############################################################################

## Headless Service Configuration
headless:
  enabled: false                # Enable headless service
  # Optional: define a custom selector if needed:
  # selector:
  #   app: "custom-headless-selector"

## Ingress Configuration
ingress:
  enabled: false                # Enable/disable Ingress
  className: cilium             # Ingress class name
  tls:
    certManagerIssuer: letsencrypt-prod  # Cert-manager issuer for TLS certificates

## Gateway Configuration (HTTPRoute)
gateway:
  enabled: false                # Enable/disable HTTPRoute
  name: gateway-internal        # Name of the Gateway
  namespace: network            # Namespace of the Gateway
  domain: sulibot.com           # Default domain for hostnames

###############################################################################
# Additional Customization
###############################################################################
env: []                         # Additional environment variables
# Example:
# - name: ENV_VAR_1
#   value: "value1"

labels:
  global: {}                    # Global labels applied to all resources

annotations:
  pod: {}                       # Pod-level annotations
