# values.yaml
#
# This file provides default configuration values for your Helm chart.

###############################################################################
# Release Name and Namespace
###############################################################################
# Used in templates for naming resources and setting the deployment namespace.
name: app-name
namespace: media

###############################################################################
# Container Image Configuration
###############################################################################
# Configure the container repository, tag, and pull policy.
image:
  repository: my-container-repo       # e.g., docker.io/library/nginx
  tag: latest
  pullPolicy: IfNotPresent

###############################################################################
# Application Replica and Ports
###############################################################################
replicaCount: 1

# Ports used by the container and Kubernetes Service.
ports:
  - name: web-ui
    servicePort: 80             # The Service port inside the cluster
    targetPort: 8080            # Container port
  - name: admin-ui
    servicePort: 8443             # The Service port inside the cluster
    targetPort: 8443           # Container port
    protocol: HTTP


###############################################################################
# Timezone
###############################################################################
timezone: "America/Los_Angeles"

###############################################################################
# DNS Settings
###############################################################################
dnsPolicy: ClusterFirst
dnsConfig:
  enabled: false
  options:
    - name: ndots
      value: "1"

###############################################################################
# Persistent Volume Claims (PVCs)
###############################################################################
# Configure PVCs for config and data volumes. Storage classes and claim names
# can be overridden here to match your environment.
config:
  enabled: true
  mountPath: /config
  storageSize: 100Mi
  storageClassName: "cephfs-csi-sc-retain"

data:
  enabled: true
  mountPath: /data
  storageSize: 10Gi
  claimName: "cephfs-pvc-media"

# Additional volume mounts or volumes can be specified below.
volumeMountsExtras: []
volumesExtras: []

###############################################################################
# Security Contexts
###############################################################################
# Control the user/group IDs and other security settings at the pod/container level.

podSecurityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  # Uncomment and adjust if you need additional container capabilities:
  # config:
  #   capabilities:
  #     add:
  #       - SETGID

###############################################################################
# Health Probes (Liveness, Readiness, Startup)
###############################################################################
probes:
  liveness:
    enabled: false
    path: /healthz
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: false
    path: /ready
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  startup:
    enabled: false
    path: /startup
    port: 8080
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1

###############################################################################
# Resource Requests and Limits
###############################################################################
# Enable this to set CPU/memory requests and limits for the container.
resources:
  enabled: false
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

###############################################################################
# Global Networking Options
###############################################################################
# ipFamilyPolicy can be PreferDualStack, RequireDualStack, or SingleStack.
# If SingleStack is chosen, singleStackIPFamily is used.
networking:
  ipFamilyPolicy: PreferDualStack
  singleStackIPFamily: IPv4

###############################################################################
# Scheduling: Tolerations and Affinity
###############################################################################
tolerations: []

affinity:
  enabled: true
  nodeAffinity:
    # requiredDuringSchedulingIgnoredDuringExecution: {}
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: intel.feature.node.kubernetes.io/gpu
              operator: In
              values:
                - "true"
      - weight: 1
        preference:
          matchExpressions:
            - key: topology.kubernetes.io/host
              operator: In
              values:
                - pve01
                - pve02
                - pve03
  # Example for podAffinity/podAntiAffinity:
  # podAffinity: {}
  # podAntiAffinity: {}

###############################################################################
# Service, Ingress, and Gateway Configuration
###############################################################################
headless:
  enabled: false
  # selector:
  #   app: "my-custom-headless-selector"

ingress:
  enabled: false
  className: cilium
  tls:
    certManagerIssuer: letsencrypt-prod

gateway:
  enabled: true
  name: gateway-internal
  namespace: network
  domain: sulibot.com
  additionalHostnames: []
  # e.g. ["secondary"]

###############################################################################
# Additional Environment Configuration
###############################################################################
env: []
  # - name: ENV_VAR_1
  #   value: "value1"

envFrom:
  - secretRef:
      name: twenty-config-secret

###############################################################################
# Additional Labels and Annotations
###############################################################################
labels:
  global: {}

annotations:

###############################################################################
# Optional Custom Commands and Arguments
###############################################################################
# command:
#   - "filebrowser"
# args:
#   - "-r"
#   - "/srv"
#   - "-a"
#   - "0.0.0.0"
#   - "-p"
#   - "8080"
