{{- if .Values.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.config.resources.requests.storage | default "1Gi" }}
  storageClassName: csi-cephfs-sc
{{- end }}
