{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config-pvc  # Automatically append "-config-pvc" to the app name
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce  # Always ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
  storageClassName: {{ .Values.pvc.storageClassName | default "csi-cephfs-sc" }}
{{- end }}
