apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-template.fullname" . }}-config-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "chart-template.defaultConfigStorage" . }}
  storageClassName: csi-cephfs-sc
