apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart-template.fullname" . }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include "chart-template.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "deployment"
    app.kubernetes.io/managed-by: "Helm"
    {{- with (default dict .Values.labels.global) }}{{ toYaml . | nindent 4 }}{{- end }}
    {{- with (default dict .Values.labels.deployment) }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with (default dict .Values.annotations.global) }}{{ toYaml . | nindent 4 }}{{- end }}
    {{- with (default dict .Values.annotations.deployment) }}{{ toYaml . | nindent 4 }}{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "chart-template.fullname" . }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "chart-template.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/component: "deployment"
        app.kubernetes.io/managed-by: "Helm"
        {{- with (default dict .Values.labels.global) }}{{ toYaml . | nindent 8 }}{{- end }}
        {{- with (default dict .Values.labels.pod) }}{{ toYaml . | nindent 8 }}{{- end }}
      annotations:
        {{- with (default dict .Values.annotations.global) }}{{ toYaml . | nindent 8 }}{{- end }}
        {{- with (default dict .Values.annotations.pod) }}{{ toYaml . | nindent 8 }}{{- end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: "{{ include "chart-template.fullname" . }}"
          image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.ports.targetPort }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
          resources:
            {{- if .Values.resources.enabled }}
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shared-media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: "{{ include "chart-template.fullname" . }}-config-pvc"
        - name: shared-media
          persistentVolumeClaim:
            claimName: "shared-media-pvc"
