apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-template.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "chart-template.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart-template.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "chart-template.fullname" . }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
      containers:
        - name: {{ include "chart-template.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.ports.targetPort }}
          env:
            - name: TZ
              value: "{{ .Values.timezone | default "America/Los_Angeles" }}"  # Use timezone from values.yaml
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
            limits:
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
          {{- end }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: config
              mountPath: {{ .Values.config.mountPath | default "/config" }}
            {{- end }}
            {{- if .Values.sharedMedia.enabled }}
            - name: shared-media
              mountPath: {{ .Values.sharedMedia.mountPath | default "/media" }}
            {{- end }}
      volumes:
        {{- if .Values.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-config-pvc
        {{- end }}
        {{- if .Values.sharedMedia.enabled }}
        - name: shared-media
          persistentVolumeClaim:
            claimName: shared-media-pvc
        {{- end }}
