apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart-template.fullname" . }}-route
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "chart-template.labels" (dict "resourceType" "httproute" "Values" .Values) | nindent 4 }}
  annotations:
    {{- include "chart-template.annotations" (dict "resourceType" "httproute" "Values" .Values) | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | default "gateway-internal" }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ printf "%s.%s" .Values.name .Values.gateway.domain | default "sulibot.com" }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "chart-template.fullname" . }}-service
          namespace: {{ .Values.namespace }}
          port: {{ .Values.ports.servicePort }}
