apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "chart-template.fullname" . }}-route
  namespace: {{ .Values.gateway.namespace }}  # Same namespace as the Gateway
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  hostnames:
    - {{ .Values.host }}  # Default to app-name.sulibot.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "chart-template.fullname" . }}-service
          namespace: {{ .Values.namespace }}
          port: {{ .Values.ports.servicePort }}
