apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart-template.fullname" . }}-route
  namespace: {{ .Values.gateway.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chart-template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: httproute
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: "Annotations for httproute"
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ printf "%s.%s" (default "default-name" .Values.name) (default "example.com" .Values.gateway.domain) }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "chart-template.fullname" . }}-service
          namespace: {{ .Values.namespace }}
          port: 80
