apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart-template.fullname" . }}-route
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - name: {{ include "chart-template.gatewayName" . }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ include "chart-template.hostname" . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "chart-template.fullname" . }}-service
          namespace: {{ .Values.namespace }}
          port: {{ .Values.ports.servicePort }}
