apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart-template.fullname" . }}-service"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include "chart-template.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/managed-by: "Helm"
    {{- with .Values.labels.global }}
{{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.labels.service }}
{{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations.global }}
{{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations.service }}
{{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: "{{ include "chart-template.fullname" . }}"
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.targetPort }}
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
