apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-template.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart-template.labels" (dict "resourceType" "service" "Values" .Values "Release" (dict "Name" (.Release.Name | default "default-release") "Service" (.Release.Service | default "Helm")) "Chart" .Chart) | nindent 4 }}
  annotations:
    {{- include "chart-template.annotations" (dict "resourceType" "service" "Values" .Values) | nindent 4 }}
spec:
  selector:
    app: {{ include "chart-template.fullname" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.targetPort }}
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
