apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "chart-template.fullname" . }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include "chart-template.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "statefulset"
    app.kubernetes.io/managed-by: "Helm"
    {{- with (default dict .Values.labels.global) }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with (default dict .Values.labels.statefulset) }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with (default dict .Values.annotations.global) }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with (default dict .Values.annotations.statefulset) }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "chart-template.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "chart-template.fullname" . }}"
        app.kubernetes.io/name: "{{ include "chart-template.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/component: "statefulset"
        app.kubernetes.io/managed-by: "Helm"
        {{- with (default dict .Values.labels.global) }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with (default dict .Values.labels.pod) }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with (default dict .Values.annotations.global) }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with (default dict .Values.annotations.pod) }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: "{{ include "chart-template.fullname" . }}"
          image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.ports.targetPort }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            {{- with .Values.env }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          {{- end }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: config
              mountPath: "{{ .Values.config.mountPath }}"
            {{- end }}
            {{- if .Values.data.enabled }}
            - name: data
              mountPath: "{{ .Values.data.mountPath }}"
            {{- end }}
      volumes:
        {{- if .Values.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: "data-cephfs-pvc"  # Reference to existing PVC
        {{- end }}
      tolerations:
        {{- if .Values.tolerations }}
        {{ toYaml .Values.tolerations | nindent 6 }}
        {{- end }}
      affinity:
        {{- if .Values.affinity }}
        {{ toYaml .Values.affinity | nindent 6 }}
        {{- end }}
  {{- if .Values.config.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app: "{{ include "chart-template.fullname" . }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.config.storageSize | default "1Gi" }}"
        storageClassName: "csi-cephfs-sc-retain"
  {{- end }}
